import os

print(os.getcwd())

from snakemake.utils import min_version
from snakemake.io import load_configfile

from pathlib import Path

from pathlib import Path
import os
min_version("6.0")
print(os.listdir())
module pypsa:
    snakefile:
        Path("rules/pypsa.smk")
    config:
        {
            **load_configfile(Path("config.tutorial.yaml")),
            **load_configfile(Path("configs/bundle_config.yaml"))
        }

use rule * from pypsa
